version: '3'

services:
  wcfhost_lgb:
    image: furbor/wcfhost-lgb
    build: ./Host
    container_name: Host
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
      - 8733:8733

  wcfclient_lgb:
    image: furbor/wcfclient-lgb
    build: ./HeavyClient
    container_name: Client
    stdin_open: true
    tty: true
    depends_on: 
      - wcfhost_lgb
    environment:
        host: wcfhost_lgb:8080