FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.2 AS build
WORKDIR /app
COPY Host/. .
RUN msbuild -restore /p:Configuration=Release

FROM mcr.microsoft.com/dotnet/framework/runtime:4.7.2 AS runtime
EXPOSE 8080
WORKDIR /app
COPY --from=build /app/bin/Release .
ENTRYPOINT ["Host.exe"]