version: '3'

services:
  wcfhost_lgb:
    image: furbor/wcfhost-lgb
    build: ./Host
    container_name: Host
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    networks:
      - lgb-network

  wcfclient_lgb:
    image: furbor/wcfclient-lgb
    build: ./HeavyClient
    container_name: Client
    stdin_open: true
    tty: true
    depends_on: 
      - wcfhost_lgb
    environment:
        host: wcfhost_lgb:8080
    networks:
      - lgb-network

networks:
  lgb-network:
    driver: bridge