version: '3'

services:
  wcfhost_lgb:
    image: furbor/wcfhost-lgb
    build: ./Host
    container_name: Host
    ports:
      - 8080:8080

  wcfclient_lgb:
    image: furbor/wcfclient-lgb
    build: ./HeavyClient
    container_name: Client
    depends_on: 
      - wcfhost_lgb