//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavyClient.JCDecaux {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JCDecauxItem", Namespace="http://schemas.datacontract.org/2004/07/Proxy.Models")]
    [System.SerializableAttribute()]
    public partial class JCDecauxItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HeavyClient.JCDecaux.JCDecauxItem.Station[] stationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HeavyClient.JCDecaux.JCDecauxItem.Station[] stations {
            get {
                return this.stationsField;
            }
            set {
                if ((object.ReferenceEquals(this.stationsField, value) != true)) {
                    this.stationsField = value;
                    this.RaisePropertyChanged("stations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="JCDecauxItem.Station", Namespace="http://schemas.datacontract.org/2004/07/Proxy.Models")]
        [System.SerializableAttribute()]
        public partial class Station : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string addressField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int available_bike_standsField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int available_bikesField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int bike_standsField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string contract_nameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string nameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int numberField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private HeavyClient.JCDecaux.JCDecauxItem.Position positionField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string statusField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string address {
                get {
                    return this.addressField;
                }
                set {
                    if ((object.ReferenceEquals(this.addressField, value) != true)) {
                        this.addressField = value;
                        this.RaisePropertyChanged("address");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int available_bike_stands {
                get {
                    return this.available_bike_standsField;
                }
                set {
                    if ((this.available_bike_standsField.Equals(value) != true)) {
                        this.available_bike_standsField = value;
                        this.RaisePropertyChanged("available_bike_stands");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int available_bikes {
                get {
                    return this.available_bikesField;
                }
                set {
                    if ((this.available_bikesField.Equals(value) != true)) {
                        this.available_bikesField = value;
                        this.RaisePropertyChanged("available_bikes");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int bike_stands {
                get {
                    return this.bike_standsField;
                }
                set {
                    if ((this.bike_standsField.Equals(value) != true)) {
                        this.bike_standsField = value;
                        this.RaisePropertyChanged("bike_stands");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string contract_name {
                get {
                    return this.contract_nameField;
                }
                set {
                    if ((object.ReferenceEquals(this.contract_nameField, value) != true)) {
                        this.contract_nameField = value;
                        this.RaisePropertyChanged("contract_name");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string name {
                get {
                    return this.nameField;
                }
                set {
                    if ((object.ReferenceEquals(this.nameField, value) != true)) {
                        this.nameField = value;
                        this.RaisePropertyChanged("name");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int number {
                get {
                    return this.numberField;
                }
                set {
                    if ((this.numberField.Equals(value) != true)) {
                        this.numberField = value;
                        this.RaisePropertyChanged("number");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public HeavyClient.JCDecaux.JCDecauxItem.Position position {
                get {
                    return this.positionField;
                }
                set {
                    if ((object.ReferenceEquals(this.positionField, value) != true)) {
                        this.positionField = value;
                        this.RaisePropertyChanged("position");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string status {
                get {
                    return this.statusField;
                }
                set {
                    if ((object.ReferenceEquals(this.statusField, value) != true)) {
                        this.statusField = value;
                        this.RaisePropertyChanged("status");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="JCDecauxItem.Position", Namespace="http://schemas.datacontract.org/2004/07/Proxy.Models")]
        [System.SerializableAttribute()]
        public partial class Position : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double latitudeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double longitudeField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double latitude {
                get {
                    return this.latitudeField;
                }
                set {
                    if ((this.latitudeField.Equals(value) != true)) {
                        this.latitudeField = value;
                        this.RaisePropertyChanged("latitude");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public double longitude {
                get {
                    return this.longitudeField;
                }
                set {
                    if ((this.longitudeField.Equals(value) != true)) {
                        this.longitudeField = value;
                        this.RaisePropertyChanged("longitude");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCDecaux.IJCDecaux")]
    public interface IJCDecaux {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecaux/GetAllStations", ReplyAction="http://tempuri.org/IJCDecaux/GetAllStationsResponse")]
        HeavyClient.JCDecaux.JCDecauxItem GetAllStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecaux/GetAllStations", ReplyAction="http://tempuri.org/IJCDecaux/GetAllStationsResponse")]
        System.Threading.Tasks.Task<HeavyClient.JCDecaux.JCDecauxItem> GetAllStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecaux/GetAllStationsFromCity", ReplyAction="http://tempuri.org/IJCDecaux/GetAllStationsFromCityResponse")]
        HeavyClient.JCDecaux.JCDecauxItem GetAllStationsFromCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecaux/GetAllStationsFromCity", ReplyAction="http://tempuri.org/IJCDecaux/GetAllStationsFromCityResponse")]
        System.Threading.Tasks.Task<HeavyClient.JCDecaux.JCDecauxItem> GetAllStationsFromCityAsync(string city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJCDecauxChannel : HeavyClient.JCDecaux.IJCDecaux, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JCDecauxClient : System.ServiceModel.ClientBase<HeavyClient.JCDecaux.IJCDecaux>, HeavyClient.JCDecaux.IJCDecaux {
        
        public JCDecauxClient() {
        }
        
        public JCDecauxClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JCDecauxClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HeavyClient.JCDecaux.JCDecauxItem GetAllStations() {
            return base.Channel.GetAllStations();
        }
        
        public System.Threading.Tasks.Task<HeavyClient.JCDecaux.JCDecauxItem> GetAllStationsAsync() {
            return base.Channel.GetAllStationsAsync();
        }
        
        public HeavyClient.JCDecaux.JCDecauxItem GetAllStationsFromCity(string city) {
            return base.Channel.GetAllStationsFromCity(city);
        }
        
        public System.Threading.Tasks.Task<HeavyClient.JCDecaux.JCDecauxItem> GetAllStationsFromCityAsync(string city) {
            return base.Channel.GetAllStationsFromCityAsync(city);
        }
    }
}
